import sys
import os
import asyncio

# Add the backend and parent directories to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), ".")))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "backend")))

from backend.models import MAXY1_3

async def gather_answers():
    queries = [
        "Create a dark theme portfolio website",
        "Explain how React hooks work in depth",
        "Write an essay on the importance of renewable energy",
        "Write a speech about space exploration for students"
    ]
    
    with open("answers_verification.md", "w", encoding="utf-8") as f:
        f.write("# MAXY 1.3 - Test Query Answers & Verification\n\n")
        f.write("This document contains the full responses generated by MAXY 1.3 for the verification queries used during the integration process.\n\n")
        
        for query in queries:
            print(f"Processing: {query}")
            result = MAXY1_3.process_message(query)
            response = result.get('response', 'No response generated.')
            
            f.write(f"## Query: {query}\n\n")
            f.write(f"{response}\n\n")
            f.write("---\n\n")
            
            await asyncio.sleep(2) # Prevent rate limits

if __name__ == "__main__":
    asyncio.run(gather_answers())
